# ===============================
# APPLICATION
# ===============================
spring.application.name=SpringBootDemo

# ===============================
# DEVTOOLS (Development Only)
# ===============================
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=500ms
spring.devtools.restart.quiet-period=200ms

server.port=8080